// <auto-generated />
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230811081125_Initilize")]
    partial class Initilize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Non-Alcoholic Beverages",
                            DisplayOrder = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Wine",
                            DisplayOrder = 2
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Snacks",
                            DisplayOrder = 3
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Coca Cola"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Yellow Tail"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Trinchero Family Estates"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Frito Lay"
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DozenPrice")
                        .HasColumnType("float");

                    b.Property<double>("HalfDozenPrice")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "The primary taste of Coca-Cola is thought to come from vanilla and cinnamon, with trace amounts of essential oils, and spices such as nutmeg.",
                            DozenPrice = 0.98999999999999999,
                            HalfDozenPrice = 1.24,
                            ImageUrl = "/images/products/Coke.jpg",
                            ListPrice = 1.99,
                            ManufacturerId = 1,
                            Name = "Coca Cola Classic",
                            Size = "33cl",
                            UPC = "4894034",
                            UnitPrice = 1.49
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "<p>The Yellow Tail Shiraz has a deep red color with bright purple hues, characteristic of fine young wines. It displays impressive <strong>spice, licorice, and black currant aromas</strong>. The palate is perfectly balanced with soft tannins and fine French Oak, further complemented by ripe fruit flavors.</p>",
                            DozenPrice = 6.9900000000000002,
                            HalfDozenPrice = 7.9900000000000002,
                            ImageUrl = "/images/products/YellowTail.png",
                            ListPrice = 9.9900000000000002,
                            ManufacturerId = 2,
                            Name = "Yellow Tail Shiraz",
                            Size = "750 ml",
                            UPC = "031259008943",
                            UnitPrice = 8.9900000000000002
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Menage a Trois California Red Blend exposes the fresh, ripe, jam-like fruit that is the calling card of California wine. Forward, spicy and soft, this delicious dalliance makes the perfect accompaniment for grilled meats or chicken.",
                            DozenPrice = 9.9900000000000002,
                            HalfDozenPrice = 10.75,
                            ImageUrl = "/images/products/menage.jpg",
                            ListPrice = 12.99,
                            ManufacturerId = 3,
                            Name = "Menage a Trois Merlot",
                            Size = "750 ml",
                            UPC = "099988071096",
                            UnitPrice = 11.49
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "The chip that packs a flavorful punch with the classic crunch. Boldly seasoned with three cheeses, tomatoes, onions, and a savory blend of spices. Indulge yourself or share with large gatherings",
                            DozenPrice = 0.68999999999999995,
                            HalfDozenPrice = 1.05,
                            ImageUrl = "/images/products/doritos.jpg",
                            ListPrice = 1.99,
                            ManufacturerId = 4,
                            Name = "Doritos",
                            Size = "175 grams",
                            UPC = "028400443753",
                            UnitPrice = 1.49
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "The fun, crunchy snack that is made with real cheese. Packed with flavor that satisfies. Always a crowd favorite.",
                            DozenPrice = 0.68999999999999995,
                            HalfDozenPrice = 1.05,
                            ImageUrl = "/images/products/cheetos.jpg",
                            ListPrice = 1.99,
                            ManufacturerId = 4,
                            Name = "Cheetos",
                            Size = "200 grams",
                            UPC = "028400443661",
                            UnitPrice = 1.49
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Product", b =>
                {
                    b.HasOne("DataAccess.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });
#pragma warning restore 612, 618
        }
    }
}
